app = "domainspotter"
primary_region = "ord"

[env]
ENV = "prod"

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1

[[checks]]
  type = "http"
  name = "homepage"
  interval = "10s"
  timeout = "3s"
  grace_period = "2s"
  method = "get"
  path = "/"

[deploy]
  strategy = "rolling"
